FIND_PATH(HELLO_INCLUDE_DIR hello.h /tmp/t3/usr/include/hello /usr/include/hello /usr/local/include/hello)
FIND_LIBRARY(HELLO_LIBRARY hello PATH /tmp/t3/usr/lib /usr/lib /usr/local/lib) 

MESSAGE(STATUS "Found Hello Library: ${HELLO_LIBRARY}")
MESSAGE(STATUS "Found Hello include: ${HELLO_INCLUDE_DIR}")

IF (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
 SET(HELLO_FOUND TRUE)
ENDIF (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF (HELLO_FOUND)
 IF (NOT HELLO_FIND_QUIETLY)
    MESSAGE(STATUS "Found Hello: ${HELLO_LIBRARY}")
 ENDIF (NOT HELLO_FIND_QUIETLY)
ELSE (HELLO_FOUND)
 IF (HELLO_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find hello library")
 ENDIF (HELLO_FIND_REQUIRED)
ENDIF (HELLO_FOUND)
